### ISSUE TITLE
Attribute Error while trying to delete a row using Python.

### ISSUE THREAD

**Issue by VRtheKing** [supabase-community/postgrest-py#8] opened 2021-07-28 08:17 UTC
### Bug Report

When I tried to Delete a row from a table using Python it returned a Error.

**To Reproduce:**

```python
import os
from supabase_py import create_client, Client

url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_KEY")
supabase: Client = create_client(url, key)
data = supabase.from_("repl").eq("name", "Africa").delete().execute()
```

## Expected behavior

You should get this Error.
```python
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    r = supabase.table("repl").eq("id", "name").delete().execute()
AttributeError: 'RequestBuilder' object has no attribute 'eq'
```

**Comment by owlnai** [comment] 2021-07-28 08:35
I've tried to reproduce the bug with a fresh new table and it results in the same error, nothing happened in the table. However, I was able to delete rows matching a filter with this code:
```Python
supabase.from_("events").delete().eq("id", "2").execute()
```

Although it did delete the rows, the command ended in a fatal error when trying to parse the JSON of the response. Here's the full traceback:
```Python
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    supabase.from_("events").delete().eq("id", "2").execute()
  File "C:\Python38\lib\site-packages\supabase_py\lib\query_builder.py", line 33, in _execute_monkey_patch
    "data": response.json(),
  File "C:\Python38\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by keosariel** [comment] 2021-08-16 22:31
When you make a `DELETE` request, the response is `None` if successful and it's can't be serialized because you can't convert a `None` type to JSON. We'd need data to be `None` if request method is `DELETE`

**Comment by dreinon** [comment] 2022-01-04 13:07
Hi! Closing this issue since it has already been solved in the current version or before. Thanks for reporting :slightly_smiling_face:!

**Closed by dreinon** 2022-01-04 13:07 UTC
Labels: bug
