### ISSUE TITLE
JSONDecodeError when inserting

### ISSUE THREAD

**Issue by jenswilms** [supabase-community/postgrest-py#192] opened 2022-12-16 08:12 UTC
**Describe the bug**
I'm getting a JSON Decode Error in SyncQueryRequestBuilder.execute. Any idea what happened?

Exact error message:
```
File ~/.asdf/installs/python/3.11.0/lib/python3.11/site-packages/postgrest/_sync/request_builder.py:62, in SyncQueryRequestBuilder.execute(self)
     53 r = self.session.request(
     54     self.http_method,
     55     self.path,
   (...)
     58     headers=self.headers,
     59 )
     61 try:
---> 62     return APIResponse.from_http_request_response(r)
     63 except ValidationError as e:
     64     raise APIError(r.json()) from e
...
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**To Reproduce**
```
import os

from supabase import create_client, Client

url: str = os.getenv("SUPABASE_URL")
key: str = os.getenv("SUPABASE_KEY")
supabase: Client = create_client(url, key)

def storeRepos(toAddRepos):

    #fetch current repos
    supabaseCurrentRepos = supabase.table("repos").select("name").execute()
    currentRepos = [r["name"] for r in supabaseCurrentRepos.data]
    
    for repo in toAddRepos:
        # check if already exist
        if currentRepos.count(repo["name"]) == 0:
            repo["scraped"] = False
            supabase.table("repos").insert(repo).execute()
            currentRepos.append(repo["name"])
    
storeRepos(testrepo)
```
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- OS using Python 3.11.0

**Additional context**

**Comment by J0** [comment] 2023-02-12 08:11
Hey,

Just tested insert and it seems to work now - this was probably caused by the way Python3.11 handles stringification of Enums leading to an invalid query.

 Going to close this issue but feel free to reopen if there are issues

**Closed by J0** 2023-02-12 08:11 UTC
