### ISSUE TITLE
Foreign tables filtering issue

### ISSUE THREAD

**Issue by tbrains** [supabase-community/postgrest-py#123] opened 2022-05-03 16:26 UTC
When filtering on a foreign table column, the function sanitize_param adds extra quotes if the param has restricted characters, this breaks and throws an error.

'foreign_table.col1' -> sanitize_param -> '"foreign_table.col1"'

I checked, by removing the extra quotes, the filter works as expected. sanitize_param is used twice => filter() and in_().

What do you suggest?

**Comment by anand2312** [comment] 2022-05-05 06:05
Duplicate of supabase-community/supabase-py#203 ; we'll get to fixing this soon. Thanks for the report!

**Comment by J0** [comment] 2023-02-07 13:22
Closing in favour of tracking on #189

**Closed by J0** 2023-02-07 13:22 UTC
Labels: duplicate
