### ISSUE TITLE
PGRST102: Error in $: not enough input when inserting data using supabase-py

### ISSUE THREAD

**Issue by goodmarvin** [supabase-community/postgrest-py#305] opened 2023-05-11 16:30 UTC
Trying to update a row using the supabase.table().update().eq().execute() pattern. Using postman to test my API it keeps returning the error "PGRST102: Error in $: not enough input" 

Googling this error, I came across a [similar issue](https://github.com/supabase/supabase/issues/7293) that popped up with the JS version of supabase. (There error that time was it seems that this happened because an exception during the JWT decoding caused cloudflare workers to resend the request without a body(hence the error message)"

**Comment by goodmarvin** [comment] 2023-09-19 14:47
@J0 Had to move to a different database provider because I couldn't get this to work. Love Supabase for my node projects, but I've really had a tough time getting things to work as I'd like them in python.

**Comment by anand2312** [comment] 2023-10-01 14:01
Anyone still facing this issue - can you enable [debug logging](https://postgrest-py.readthedocs.io/en/latest/examples/logging.html) and send the logs for the requests that httpx sends? I'm not able to reproduce this right now so it'd help give me some leads about what's causing this issue

**Comment by anand2312** [comment] 2023-10-01 15:04
Also please make sure you're on the latest version of this package, AND that you haven't accidentally installed the wrong package. The latest version is installed with `pip install supabase`, installing `supabase-py` gives you an outdated version

**Comment by anand2312** [comment] 2023-10-02 18:26
I'll be closing this now as I've not been able to reproduce this error with the latest version of this package - previous instances of people encountering this bug was due to the wrong package (`supabase-py` instead of `supabase`) being installed. If this issue still exists on the latest version, feel free to reopen.

**Closed by anand2312** 2023-10-02 18:26 UTC

**Comment by Yumat10** [comment] 2023-10-03 18:05
I had a similar issue. I had, in fact, installed `supabase-py` instead of `supabase`. Thanks for the help!
